CREATE TABLE IF NOT EXISTS SOURCE_PERSON (
    ID INT,
    NAME VARCHAR(128),
    AGE INT
);

CREATE TABLE IF NOT EXISTS TARGET_PERSON (
    ID INT,
    NAME VARCHAR(128),
    SURNAME VARCHAR(128),
    AGE INT
);