DELETE FROM SOURCE_PERSON;
DELETE FROM TARGET_PERSON;

INSERT INTO SOURCE_PERSON(ID, NAME, AGE) VALUES (1, 'Mark', 42);
INSERT INTO SOURCE_PERSON(ID, NAME, AGE) VALUES (2, 'Natasja', 41);
INSERT INTO SOURCE_PERSON(ID, NAME, AGE) VALUES (3, 'Dillon', 16);

INSERT INTO TARGET_PERSON(ID, NAME, SURNAME, AGE) VALUES (1, 'Marcus', 'Ashworth', 43);
INSERT INTO TARGET_PERSON(ID, NAME, SURNAME, AGE) VALUES (2, 'Natasja', 'Olivier', 42);
INSERT INTO TARGET_PERSON(ID, NAME, SURNAME, AGE) VALUES (4, 'Crystal', 'Ashworth', 15);
INSERT INTO TARGET_PERSON(ID, NAME, SURNAME, AGE) VALUES (5, 'Katie', 'Puppy', 5);
INSERT INTO TARGET_PERSON(ID, NAME, SURNAME, AGE) VALUES (6, 'Shadow', 'Cat', 5);